### ISSUE TITLE
(field 'getJob')

### ISSUE THREAD

**Issue by d1ckofsheep** [stevoscriptsteam/stevo_policebadge#5]
SCRIPT ERROR: @stevo_policebadge/resource/server.lua:15: attempt to call a nil value (field 'getJob')

Got this when showing badge.

**Comment by stevoscriptsteam** [comment]
Resolved,get latest version of policebadge and lib

**Comment by d1ckofsheep** [comment]
> Resolved,get latest version of policebadge and lib

Its not fixed , same error .
I download lastest version of both script.

**Comment by stevoscriptsteam** [comment]
There is no getJob on the server side of the police badge
